name: Build, validate, and publish if on master

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Pandoc 2.6
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.6/pandoc-2.6-1-amd64.deb
        sudo dpkg -i pandoc-2.6-1-amd64.deb
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build
        npm run validate
      env:
        LANG: en_US.UTF-8
        CI: true
    - name: Publish to a CouchDB database if on master
      if: github.event_name == 'push' && github.ref == 'refs/heads/feat/auto-publish'
      run: |
        npm run clean-couchdb
        npm run upload
      env:
        COUCH_URL: ${{ secrets.COUCH_URL }}
        IAM_API_KEY: ${{ secrets.IAM_API_KEY }}
